# _targets.R file
library(targets)
source("R/functions.R")
library(crew)
library(tarchetypes)

tar_option_set(packages = c("data.table", "dplyr", "ENMeval","janitor", "magrittr", "maxnet", "purrr", "Rarity", "readxl",
                            "SDMWorkflows", "stringr", "tidyr", "tibble","terra", "V.PhyloMaker", "BDRUtils", "readr"),
               controller = crew_controller_local(workers = 4),
               error = "null") # Force skip non-debugging outdated targets)
list(
  tar_target(LanduseSuitability,
             "HabSut/Aarhus.tif",
             format = "file"),
  tar_target(LandUseTiff,
             "Dir/LU_Aarhus.tif",
             format = "file"),
  tar_target(Species_cover,
             "feltdata_exisiting_nature_plots.rds",
             format = "file"),
  tarchetypes::tar_group_by(field_presences, get_field_presences(Species_cover), species),
  tar_target(Species_newnature,
             "feltdata_new_nature_plots.csv",
             format = "file"),
  tarchetypes::tar_group_by(field_presences_newnature, get_field_presences_csv(Species_newnature), species),
  tar_target(Species_observations,
             bind_rows(field_presences,field_presences_newnature)),
  tar_target(Presences,
             get_plant_presences(Filter_Counts),
             pattern = map(Filter_Counts)),
  tar_target(buffer_500, make_buffer_rasterized(DT = field_presences, file = LandUseTiff),
             pattern = map(field_presences),
             iteration = "group"),
  tar_target(Long_Buffer, make_long_buffer(DT = buffer_500),
             pattern = map(buffer_500),
             iteration = "group"),
  tar_target(Phylo_Tree, generate_tree(field_presences)),
  tar_target(ModelAndPredict, ModelAndPredictFunc(DF =  field_presences, file = LandUseTiff),
             pattern = map(field_presences)),
             #iteration = "group"),
  tar_target(Thresholds, create_thresholds(Model = ModelAndPredict,reference = field_presences, LandUseTiff),
             pattern = map(ModelAndPredict, field_presences),
             iteration = "group"),
  tar_target(LookUpTable, Generate_Lookup(Model = ModelAndPredict, Thresholds = Thresholds)),
  tar_target(LanduseTable, generate_landuse_table(path = LanduseSuitability)),
  tar_target(Long_LU_table, Make_Long_LU_table(DF = LanduseTable)),
  tar_target(Final_Presences, make_final_presences(Long_LU_table, Long_Buffer, LookUpTable),
             pattern = map(Long_Buffer),
             iteration = "group"),
  tarchetypes::tar_group_by(joint_final_presences, as.data.frame(Final_Presences), Landuse),
  tar_target(rarity_weight, calc_rarity_weight(joint_final_presences)),
  tar_target(rarity, calc_rarity(joint_final_presences, rarity_weight),
             map(joint_final_presences),
             iteration = "group"),
  tar_target(PhyloDiversity,
             calc_pd(joint_final_presences, Phylo_Tree),
             map(joint_final_presences),
             iteration = "group"),
  tar_target(Richness, GetRichness(Final_Presences)),
  tar_target(name = output_Richness,
             command = export_richness(Results = PhyloDiversity, path = LandUseTiff),
             map(PhyloDiversity),
             format = "file"),
  tar_target(name = output_PD,
             command = export_pd(Results = PhyloDiversity, path = LandUseTiff),
             map(PhyloDiversity),
             format = "file"),
  tar_target(name = output_Rarity,
             command = export_rarity(Results = rarity, path = LandUseTiff),
             map(rarity),
             format = "file")
)

